select
    "AtomicNumber"
    , "Element"
    , "Symbol"
    , "AtomicMass"
    , "NumberOfNeutrons"
    , "NumberOfProtons"
    , "NumberOfElectrons"
    , "Period"
    , "Group"
    , "Phase"
    , "Radioactive"
    , "Natural"
    , "Metal"
    , "Nonmetal"
    , "Metalloid"
    , "Type"
    , "AtomicRadius"
    , "Electronegativity"
    , "FirstIonization"
    , "Density"
    , "MeltingPoint"
    , "BoilingPoint"
    , "NumberOfIsotopes"
    , "Discoverer"
    , "Year"
    , "SpecificHeat"
    , "NumberOfShells"
    , "NumberOfValence"
from {{ source('periodic_table', 'periodic_table') }}
